name: Build, Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        preset: [default, release] # Corresponds to names in CMakePresets.json

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev libgoogle-glog-dev

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build project
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Run tests
      # Presets define binary directories, so we use them to locate test executables
      run: |
        if [ "${{ matrix.preset }}" = "default" ]; then
          ./build/debug/tests/gtest/gtests
          ctest --output-on-failure --test-dir build/debug
        fi

  fuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (Clang)
      run: sudo apt-get update && sudo apt-get install -y clang libgoogle-glog-dev libgtest-dev

    - name: Configure CMake for Fuzzing
      run: cmake --preset fuzz

    - name: Build Fuzzer
      run: cmake --build --preset fuzz

    - name: Run Fuzzing for 60 seconds
      run: ./build/fuzz/tests/fuzz/avl_tree_fuzzer -max_total_time=60 -print_final_stats=1

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format libgoogle-glog-dev libgtest-dev

    - name: Run cmake configuration
      run: cmake --preset release

    - name: Run clang format
      run: cmake --build build/release --target format
